# Numpy Array operations

In [1]:
import numpy as np;

# array creation
arr = np.array([1,2,3,4]);
print(arr);

[1 2 3 4]


In [5]:
# array ops
arr1 = np.array([1,2,3]);
arr2 = np.array([10,20,30]);

print('addition - ', arr1 + arr2);
print('multiplication - ', arr1 * arr2);
print('multiplication by 2 - ', arr1 * 2);
print('addition with 5 - ', arr1 + 5);

addition -  [11 22 33]
multiplication -  [10 40 90]
multiplication by 2 -  [2 4 6]
addition with 5 -  [6 7 8]


In [6]:
# 0s and 1s
print(np.zeros([3,4]))
print(np.ones([5,9]))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [8]:
# Mean, max, min
data = np.array([10,20,30,40]);

print("Mean:", np.mean(data))
print("Max", np.max(data));
print("Min", np.min(data));

Mean: 25.0
Max 40
Min 10
