# 1. What is vectorization in NumPy?
Vectorization in NumPy is the process of performing operations on entire arrays without using explicit Python loops. NumPy executes these operations using optimized low-level implementations, making computations faster, more efficient, and more readable.

Without Vectorization:
```python
a = [1, 2, 3]
b = [4, 5, 6]


result = []

for i in range(len(a)):
    result.append(a[i] + b[i])

print(result)
```

With Vectorization:
```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
```
Output:
**[5 7 9]**

# 2. What is the difference between reshape() and resize()?
reshape() changes the dimensions of an array without changing its data size and usually returns a new array, whereas resize() modifies the original array itself and can increase or decrease the total number of elements. reshape() requires the total number of elements to remain the same, while resize() can add or remove elements.

| Feature                 | `reshape()`                      | `resize()`        |
| ----------------------- | -------------------------------- | ----------------- |
| Creates new shape       | ✅ Yes                            | ✅ Yes             |
| Changes original array  | ❌ No (usually returns new array) | ✅ Yes             |
| Data size must match    | ✅ Required                       | ❌ Can change size |
| Can add/remove elements | ❌ No                             | ✅ Yes             |
| Safer                   | ✅ Yes                            | Less safe         |


### 1. reshape():
```python
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

new_arr = arr.reshape(2, 3)

print(new_arr)
```
Output:
```python
[[1 2 3]
 [4 5 6]]
```

### 2. resize():
```python
arr = np.array([1, 2, 3])

arr.resize(5)

print(arr)
```

Output:
```python
[1 2 3 0 0]
```

# 3. What are NumPy dimensions and axes?

Dimensions in NumPy represent the number of levels or directions in an array, while axes represent the directions along which operations are performed. For example, a 2D array has two dimensions, and operations can be performed along axis 0 (column-wise) or axis 1 (row-wise).

### Dimension:
```python
arr = np.array([
    [
        [1, 2],
        [3, 4]
    ]
])

print(arr.ndim)
```
Output:
```python
3
```
It's a 3d array

### Axis:
```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
```
#### Axis 0 → Vertical Direction (Rows):
```python
print(arr.sum(axis=0))
```
Output:
```python
[5 7 9]
calcu:
(1+4 = 5
2+5 = 7
3+6 = 9)
```
#### Axis 1 → Horizontal Direction (Columns):
```python
print(arr.sum(axis=1))
```
Output:
```python
[ 6 15]  
(1+2+3 = 6
4+5+6 = 15)
```
axis=0 → move DOWN rows ,  
axis=1 → move ACROSS columns

# 4. What is slicing in NumPy arrays?

Slicing in NumPy is the process of extracting specific portions of an array using index ranges. It allows selecting subsets of elements, rows, or columns efficiently using the syntax array[start:stop:step]. Slicing is widely used in data manipulation and preprocessing tasks in AI and Data Science.

| Part    | Meaning                 |
| ------- | ----------------------- |
| `start` | starting index          |
| `stop`  | ending index (excluded) |
| `step`  | jump interval           |

```python
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
```
Output:
```python
[20 30 40]
```

# 5. How does NumPy help in mathematical computations for AI?

NumPy helps AI by providing fast and efficient numerical and mathematical computations using multidimensional arrays. It supports vectorized operations, matrix multiplication, linear algebra, statistics, broadcasting, and optimized memory handling, making it essential for Machine Learning and Deep Learning computations.

### Why AI Needs Heavy Mathematics:
Machine Learning models constantly perform:

addition , 
multiplication , 
matrix operations , 
probability calculations , 
gradient computations

For example:

neural networks , 
image processing , 
recommendation systems

all involve huge numerical calculations.